[project]
name = "tee-logger"
version = "6.19"
description = "A simple wrapper for python logger that also selectively tee logs to stdout"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "python-dateutil",
]
